# Generated by Django 5.1.7 on 2025-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_profile_postal_code_remove_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Nữ'), ('male', 'Nam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Nữ'), ('male', 'Nam')], max_length=100, null=True),
        ),
    ]
