# Generated by Django 5.1.7 on 2025-04-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_checked_in_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
