# Generated by Django 5.1.7 on 2025-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_alter_couponusers_email_alter_hotel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='momo_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vnpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='zalopay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
