# Generated by Django 5.1.7 on 2025-04-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_booking_momo_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_payment_intent',
        ),
    ]
